# -*- coding: utf-8 -*-
"""Clase_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkXwCYvZ-DRJMIWtvlfO5T_wR6gJqYSY
"""

import numpy as np
import matplotlib.pyplot as plt 
import math
import sklearn 
x = np.arange(4,30)
z= -x**2
y = x**2

plt.plot(y)
plt.plot(z)

import numpy as np
import matplotlib.pyplot as plt 
import math
import sklearn 
x = np.arange(4,30)
y = x**2- 4 + -d**2+3

plt.plot(y)